-
  name: Play 1
  hosts: ec2
  become: yes
#  become_user: ubuntu
  tasks:

    - name: "nvm"
      shell: >
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install apache2
      apt:
        pkg:
          - nodejs
          - apache2   

    - name: Install "pm2"
      npm:
        name: pm2
        global: yes

    - name: create directory
      file:
        path: /home/ubuntu/repos
        state: directory

    - name: Clone repo
      git: 
        repo: https://github.com/abkunal/Chat-App-using-Socket.io
        dest: /home/ubuntu/repos
        clone: yes
        update: yes

    - name: "install"
      command: npm install
      args:
        chdir: /home/ubuntu/repos
      register: outnetstat 
    - debug: 
        var: out.stdout_lines

    - name: "install pm2"
      command: pm2 start app.js -f
      args:
        chdir: /home/ubuntu/repos
#      register: out
#    - debug: 
#        var: out.stdout_lines

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 5000
      lineinfile: 
        path: /etc/apache2/sites-available/000-default.conf  
        insertafter: ^<VirtualHost \*:80>
        line: ProxyPass / http://localhost:5000/
        state: present

    - name: "enable proxy"
      command: a2enmod proxy
      args:
        chdir: /etc/apache2/sites-enabled
              
    - name: "enable proxy_http"
      command: a2enmod proxy_http
      args:
        chdir: /etc/apache2/sites-enabled
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

#    - name: "nvm"
#      shell: >
#        curl https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
#      register: out

#    - debug: 
#        var: out.stdout_lines


    
#    - name: Install node and set version
#      shell: >
#        source /home/ubuntu/.nvm/nvm.sh && nvm install --lts
#      args:
#        executable: /bin/bash
#      register: out

#    - debug: 
#        var: out.stdout_lines

#    - name: "Add nodejs apt key"
#      apt_key:
#        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#        state: present

#    - name: "Add nodejs 16.x ppa for apt repo"
#      apt_repository:
#        repo: deb https://deb.nodesource.com/node_16.x bionic main
#        update_cache: yes

#    - name: Update apt repo and cache
#      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
#    - name: "Install nodejs"
#      apt:
#        update_cache: yes
#        name: nodejs
#        state: present



















