-
  name: Play 1
  hosts: ec2
  become: yes
#  become_user: ubuntu
  tasks:

    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Install npm and apache2
      apt:
        pkg:
          - npm   
          - apache2   
    
#    - name: Install "forever"
#      npm:
#        name: pm2
#        global: yes

    - name: create directory
      file:
        path: /home/ubuntu/repos
        state: directory

    - name: Clone repo
      git: 
        repo: https://github.com/abkunal/Chat-App-using-Socket.io
        dest: /home/ubuntu/repos
        clone: yes
        update: yes

    - name: "nvm"
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
      register: out

    - debug: 
        var: out.stdout_lines


    
#    - name: Install node and set version
#      shell: >
#        source /home/ubuntu/.nvm/nvm.sh && nvm install --lts
#      args:
#        executable: /bin/bash
#      register: out

#    - debug: 
#        var: out.stdout_lines

#    - name: "Add nodejs apt key"
#      apt_key:
#        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#        state: present

#    - name: "Add nodejs 16.x ppa for apt repo"
#      apt_repository:
#        repo: deb https://deb.nodesource.com/node_16.x bionic main
#        update_cache: yes

#    - name: Update apt repo and cache
#      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
#    - name: "Install nodejs"
#      apt:
#        update_cache: yes
#        name: nodejs
#        state: present






















